### ISSUE TITLE
Collect German data

### ISSUE THREAD

**Issue by maltelueken** [navigating-stories/notebooks#14]
Story corpora collected so far:

- Psychologie Heute ([notebook](https://github.com/navigating-stories/notebooks/blob/main/psychologieheute.ipynb))
- Stadt Frankfurt ([notebook](https://github.com/navigating-stories/notebooks/blob/main/stadtfrankfurt.ipynb))
- Zusammen Gegen Corona ([notebook](https://github.com/navigating-stories/notebooks/blob/main/zusammengegencorona.ipynb))
- HSPV NRW ([notebook](https://github.com/navigating-stories/notebooks/blob/main/hspvnrw.ipynb); used as example in https://github.com/navigating-stories/notebooks/blob/main/ger_nlp_test.ipynb)
- Stadt Bonn ([notebook](https://github.com/navigating-stories/notebooks/blob/main/stadtbonn.ipynb))

The question is whether this is enough German data for the moment or whether we need more (given that I am not working on the project for long anymore).

Once we have decided on a format to store the data (#15), I will add the code for storing to the notebooks and make another notebook for an overview of the collected data so far.

- [x] Enough data?
- [x] #15
- [ ] Add code for data storage

**Comment by ghost** [comment]
Thanks for gathering this data Malte, I think this is a very nice collection. As far as I'm concerned this is enough German data for now. Let's discuss the storage formats next Tuesday, and then focusing on data storage is an important task to be done.
